package translator;

import java.io.*;
import java.util.*;
import java.util.regex.*;
import translator.ast.*;

public class CodeGen {
    private final Program program;
    private final String sourcePath;

    public CodeGen(Program program, String sourcePath) {
        this.program = program;
        this.sourcePath = sourcePath == null ? "" : sourcePath;
    }

    public void generate(String outputPath) throws IOException {
        try (PrintWriter out = new PrintWriter(new FileWriter(outputPath))) {
            // Header
            out.println("// Generated by TestLang++ Translator");
            out.println("// Source: " + escapeJava(this.sourcePath));
            out.println("// Generated at: " + new java.util.Date());
            out.println();
            out.println("import org.junit.jupiter.api.*;");
            out.println("import static org.junit.jupiter.api.Assertions.*;");
            out.println("import java.net.http.*; import java.net.*; import java.time.Duration;");
            out.println("import java.nio.charset.StandardCharsets; import java.util.*;");
            out.println();
            out.println("public class GeneratedTests {");
            String base = program.baseUrl != null ? escapeJava(program.baseUrl) : "";
            out.println("  static String BASE = \"" + base + "\";");
            out.println("  static Map<String,String> DEFAULT_HEADERS = new LinkedHashMap<>();");
            out.println("  static HttpClient client;");
            out.println();
            out.println("  @BeforeAll static void setup() {");
            out.println("    client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build();");
            for (Map.Entry<String,String> e : program.defaultHeaders.entrySet()) {
                out.println("    DEFAULT_HEADERS.put(\"" + escapeJava(e.getKey()) + "\",\"" + escapeJava(applyVars(e.getValue())) + "\");");
            }
            out.println("  }");
            out.println();

            for (TestBlock t : program.tests) {
                out.println("  @Test");
                out.println("  void test_" + sanitizeName(t.name) + "() throws Exception {");
                out.println("    HttpResponse<String> resp = null;");
                for (Statement s : t.statements) {
                    if (isRequest(s)) {
                        // Build a request
                        String raw = s.url != null ? s.url : "";
                        String substituted = applyVars(raw);
                        out.println("    HttpRequest.Builder b = HttpRequest.newBuilder(URI.create(resolveUrl(BASE, \"" + escapeJava(substituted) + "\")))");
                        out.println("      .timeout(Duration.ofSeconds(10))");
                        if ("GET".equals(s.type) || "DELETE".equals(s.type)) {
                            String method = "GET".equals(s.type) ? ".GET()" : ".DELETE()";
                            out.println("      " + method + ";");
                        } else if ("POST".equals(s.type) || "PUT".equals(s.type)) {
                            String body = applyVars(s.body != null ? s.body : "");
                            String method = "POST".equals(s.type) ? "POST" : "PUT";
                            out.println("      ." + method + "(HttpRequest.BodyPublishers.ofString(\"" + escapeJava(body) + "\"));");
                        } else {
                            out.println("      .GET();");
                        }
                        out.println("    for (var e: DEFAULT_HEADERS.entrySet()) b.header(e.getKey(), e.getValue());");
                        for (Map.Entry<String,String> h : s.headers.entrySet()) {
                            String hv = applyVars(h.getValue());
                            out.println("    b.setHeader(\"" + escapeJava(h.getKey()) + "\", \"" + escapeJava(hv) + "\");");
                        }
                        out.println("    resp = client.send(b.build(), HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));");
                        out.println();
                    } else if (s instanceof Assertion) {
                        Assertion a = (Assertion) s;
                        switch (a.type) {
                            case "status_eq":
                                out.println("    assertEquals(" + safeInt(a.extra) + ", resp.statusCode());");
                                break;
                            case "status_in":
                                out.println("    assertTrue(resp.statusCode() >= " + a.statusLo + " && resp.statusCode() <= " + a.statusHi + ");");
                                break;
                            case "body_contains":
                                out.println("    assertTrue(resp.body().contains(\"" + escapeJava(applyVars(a.extra)) + "\"));");
                                break;
                            case "header_eq":
                                out.println("    assertEquals(\"" + escapeJava(applyVars(a.headerValue)) + "\", resp.headers().firstValue(\"" + escapeJava(a.headerKey) + "\").orElse(\"\"));");
                                break;
                            case "header_contains":
                                out.println("    assertTrue(resp.headers().firstValue(\"" + escapeJava(a.headerKey) + "\").orElse(\"\").contains(\"" + escapeJava(applyVars(a.headerValue)) + "\"));");
                                break;
                            default:
                                out.println("    // Unsupported assertion: " + escapeJava(a.type) + ";");
                        }
                    }
                }
                out.println("  }");
                out.println();
            }

            // helper for base+path resolution
            out.println("  private static String resolveUrl(String base, String path) {");
            out.println("    if (path == null || path.isEmpty()) return base;");
            out.println("    if (path.startsWith(\"http://\") || path.startsWith(\"https://\")) return path;");
            out.println("    if (base == null || base.isEmpty()) {");
            out.println("      if (path.startsWith(\"/\")) throw new IllegalStateException(\"No base_url configured; path must be absolute\");");
            out.println("      return path;");
            out.println("    }");
            out.println("    if (path.startsWith(\"/\")) return base + path;");
            out.println("    if (base.endsWith(\"/\")) return base + path;");
            out.println("    return base + \"/\" + path;");
            out.println("  }");

            out.println("}");
        }
    }

    private static boolean isRequest(Statement s) {
        return s != null && ("GET".equals(s.type) || "POST".equals(s.type) || "PUT".equals(s.type) || "DELETE".equals(s.type));
    }

    private static String sanitizeName(String name) {
        if (name == null) return "Unnamed";
        return name.replaceAll("[^A-Za-z0-9_]", "_");
    }

    private static String escapeJava(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private String applyVars(String s) {
        if (s == null) return "";
        Pattern p = Pattern.compile("\\$[A-Za-z_][A-Za-z0-9_]*");
        Matcher m = p.matcher(s);
        StringBuffer sb = new StringBuffer();
        while (m.find()) {
            String name = m.group().substring(1);
            String replacement = program.variables.getOrDefault(name, m.group());
            m.appendReplacement(sb, Matcher.quoteReplacement(replacement));
        }
        m.appendTail(sb);
        return sb.toString();
    }

    private static int safeInt(String s) {
        try { return Integer.parseInt(s); } catch (Exception e) { return -1; }
    }
}
