// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lexer.flex

/* lexer.flex - JFlex for TestLang++ */
package translator;

import java_cup.runtime.Symbol;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\1\22\0\1\1\1\0"+
    "\1\4\13\0\1\5\1\6\12\7\1\0\1\10\1\0"+
    "\1\11\3\0\3\12\1\13\1\14\1\12\1\15\4\12"+
    "\1\16\2\12\1\17\1\20\2\12\1\21\1\22\1\23"+
    "\5\12\1\0\1\24\2\0\1\25\1\0\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\2\12"+
    "\1\37\1\12\1\40\1\41\1\42\1\12\1\43\1\44"+
    "\1\45\1\46\2\12\1\47\1\50\1\12\1\51\1\0"+
    "\1\52\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\1\1\3\1\4\1\5\14\6"+
    "\1\7\1\10\1\0\1\11\1\0\1\12\1\2\11\6"+
    "\1\13\4\6\1\14\1\6\1\15\5\6\1\16\3\6"+
    "\1\17\1\6\1\20\5\6\1\21\7\6\1\22\1\6"+
    "\1\23\1\6\1\24\1\25\1\26\2\6\1\27\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\53"+
    "\0\53\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f"+
    "\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\53\0\53\0\201"+
    "\0\53\0\u0331\0\53\0\u035c\0\u0387\0\u03b2\0\u03dd\0\u0408"+
    "\0\u0433\0\u045e\0\u0489\0\u04b4\0\u04df\0\u012d\0\u050a\0\u0535"+
    "\0\u0560\0\u058b\0\u012d\0\u05b6\0\u012d\0\u05e1\0\u060c\0\u0637"+
    "\0\u0662\0\u068d\0\u012d\0\u06b8\0\u06e3\0\u070e\0\u012d\0\u0739"+
    "\0\u012d\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u012d\0\u083b"+
    "\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u012d\0\u0968"+
    "\0\u012d\0\u0993\0\u012d\0\u012d\0\u012d\0\u09be\0\u09e9\0\u012d"+
    "\0\u012d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\12\1\14\2\12\1\15\3\12"+
    "\1\2\2\12\1\16\1\17\1\12\1\20\2\12\1\21"+
    "\1\22\1\23\4\12\1\24\1\25\3\12\1\26\1\27"+
    "\54\0\2\3\50\0\2\30\1\0\1\30\1\31\17\30"+
    "\1\32\26\30\5\0\1\33\53\0\1\34\53\0\1\7"+
    "\52\0\1\12\2\0\12\12\1\0\24\12\11\0\1\12"+
    "\2\0\2\12\1\35\7\12\1\0\24\12\11\0\1\12"+
    "\2\0\2\12\1\36\7\12\1\0\24\12\11\0\1\12"+
    "\2\0\5\12\1\37\3\12\1\40\1\0\24\12\11\0"+
    "\1\12\2\0\12\12\1\0\1\12\1\41\12\12\1\42"+
    "\7\12\11\0\1\12\2\0\12\12\1\0\14\12\1\43"+
    "\7\12\11\0\1\12\2\0\12\12\1\0\22\12\1\44"+
    "\1\12\11\0\1\12\2\0\12\12\1\0\5\12\1\45"+
    "\16\12\11\0\1\12\2\0\12\12\1\0\13\12\1\46"+
    "\10\12\11\0\1\12\2\0\12\12\1\0\5\12\1\47"+
    "\16\12\11\0\1\12\2\0\12\12\1\0\20\12\1\50"+
    "\3\12\11\0\1\12\2\0\12\12\1\0\5\12\1\51"+
    "\16\12\6\0\1\30\1\0\1\30\15\0\1\30\2\0"+
    "\1\30\3\0\1\30\4\0\1\30\2\0\1\30\1\0"+
    "\1\30\5\0\2\34\1\0\50\34\7\0\1\12\2\0"+
    "\4\12\1\52\5\12\1\0\24\12\11\0\1\12\2\0"+
    "\10\12\1\53\1\12\1\0\24\12\11\0\1\12\2\0"+
    "\7\12\1\54\2\12\1\0\24\12\11\0\1\12\2\0"+
    "\10\12\1\55\1\12\1\0\24\12\11\0\1\12\2\0"+
    "\12\12\1\0\17\12\1\56\4\12\11\0\1\12\2\0"+
    "\12\12\1\0\4\12\1\57\17\12\11\0\1\12\2\0"+
    "\12\12\1\0\13\12\1\60\10\12\11\0\1\12\2\0"+
    "\12\12\1\0\15\12\1\61\6\12\11\0\1\12\2\0"+
    "\12\12\1\0\1\12\1\62\22\12\11\0\1\12\2\0"+
    "\12\12\1\0\20\12\1\63\3\12\11\0\1\12\2\0"+
    "\12\12\1\0\1\12\1\64\22\12\11\0\1\12\2\0"+
    "\12\12\1\0\17\12\1\65\4\12\11\0\1\12\2\0"+
    "\2\12\1\66\7\12\1\0\24\12\11\0\1\12\2\0"+
    "\10\12\1\67\1\12\1\0\24\12\11\0\1\12\2\0"+
    "\12\12\1\0\5\12\1\70\16\12\11\0\1\12\2\0"+
    "\12\12\1\0\23\12\1\71\11\0\1\12\2\0\12\12"+
    "\1\0\6\12\1\72\11\12\1\73\3\12\11\0\1\12"+
    "\2\0\12\12\1\0\5\12\1\74\16\12\11\0\1\12"+
    "\2\0\12\12\1\0\4\12\1\75\17\12\11\0\1\12"+
    "\2\0\12\12\1\0\20\12\1\76\3\12\11\0\1\12"+
    "\2\0\12\12\1\0\20\12\1\77\3\12\11\0\1\12"+
    "\2\0\10\12\1\100\1\12\1\0\24\12\11\0\1\12"+
    "\2\0\12\12\1\0\1\101\23\12\11\0\1\12\2\0"+
    "\12\12\1\0\11\12\1\102\12\12\11\0\1\12\2\0"+
    "\12\12\1\0\1\12\1\103\22\12\11\0\1\12\2\0"+
    "\12\12\1\0\3\12\1\104\20\12\11\0\1\12\2\0"+
    "\12\12\1\0\5\12\1\105\16\12\11\0\1\12\2\0"+
    "\12\12\1\0\21\12\1\106\2\12\11\0\1\12\2\0"+
    "\2\12\1\107\7\12\1\0\24\12\11\0\1\12\2\0"+
    "\12\12\1\0\21\12\1\110\2\12\11\0\1\12\2\0"+
    "\12\12\1\0\7\12\1\111\14\12\11\0\1\12\2\0"+
    "\12\12\1\0\11\12\1\112\12\12\11\0\1\12\2\0"+
    "\12\12\1\0\20\12\1\113\3\12\11\0\1\12\2\0"+
    "\12\12\1\0\16\12\1\114\5\12\11\0\1\12\2\0"+
    "\12\12\1\0\17\12\1\115\4\12\11\0\1\12\2\0"+
    "\12\12\1\0\16\12\1\116\5\12\11\0\1\12\2\0"+
    "\12\12\1\0\13\12\1\117\10\12\11\0\1\12\2\0"+
    "\12\12\1\0\12\12\1\120\11\12\11\0\1\12\2\0"+
    "\12\12\1\0\17\12\1\121\4\12\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2580];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\2\11\14\1\2\11\1\0\1\11"+
    "\1\0\1\11\66\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  // helper to create Symbol with position
  private Symbol sym(int type) { return new Symbol(type, yyline+1, yycolumn+1); }
  private Symbol sym(int type, Object val) { return new Symbol(type, yyline+1, yycolumn+1, val); }

  // convert a string lexeme (including leading and trailing ") to Java unescaped value
  private String unquote(String s) {
    if (s == null || s.length() < 2) return "";
    String inner = s.substring(1, s.length()-1);
    // handle simple escapes: \" and \\ and \/
    StringBuilder sb = new StringBuilder();
    for (int i=0;i<inner.length();i++) {
      char c = inner.charAt(i);
      if (c == '\\' && i+1 < inner.length()) {
        char n = inner.charAt(i+1);
        if (n == '"' || n == '\\' || n == '/') { sb.append(n); i++; continue; }
        if (n == 'n') { sb.append('\n'); i++; continue; }
        if (n == 't') { sb.append('\t'); i++; continue; }
        // otherwise keep literal
      }
      sb.append(c);
    }
    return sb.toString();
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Lexer error at " + (yyline+1) + ":" + (yycolumn+1) + " unknown char: " + yytext());
            }
            // fall through
          case 25: break;
          case 2:
            { /* skip */
            }
            // fall through
          case 26: break;
          case 3:
            { return sym(sym.NUMBER, Integer.parseInt(yytext()));
            }
            // fall through
          case 27: break;
          case 4:
            { return sym(sym.SEMI);
            }
            // fall through
          case 28: break;
          case 5:
            { return sym(sym.EQ);
            }
            // fall through
          case 29: break;
          case 6:
            { return sym(sym.IDENT, yytext());
            }
            // fall through
          case 30: break;
          case 7:
            { return sym(sym.LBRACE);
            }
            // fall through
          case 31: break;
          case 8:
            { return sym(sym.RBRACE);
            }
            // fall through
          case 32: break;
          case 9:
            { return sym(sym.STRING, unquote(yytext()));
            }
            // fall through
          case 33: break;
          case 10:
            { return sym(sym.DOTDOT);
            }
            // fall through
          case 34: break;
          case 11:
            { return sym(sym.IN);
            }
            // fall through
          case 35: break;
          case 12:
            { return sym(sym.GET);
            }
            // fall through
          case 36: break;
          case 13:
            { return sym(sym.PUT);
            }
            // fall through
          case 37: break;
          case 14:
            { return sym(sym.LET);
            }
            // fall through
          case 38: break;
          case 15:
            { return sym(sym.POST);
            }
            // fall through
          case 39: break;
          case 16:
            { return sym(sym.BODY);
            }
            // fall through
          case 40: break;
          case 17:
            { return sym(sym.TEST);
            }
            // fall through
          case 41: break;
          case 18:
            { return sym(sym.DELETE);
            }
            // fall through
          case 42: break;
          case 19:
            { return sym(sym.CONFIG);
            }
            // fall through
          case 43: break;
          case 20:
            { return sym(sym.EXPECT);
            }
            // fall through
          case 44: break;
          case 21:
            { return sym(sym.HEADER);
            }
            // fall through
          case 45: break;
          case 22:
            { return sym(sym.STATUS);
            }
            // fall through
          case 46: break;
          case 23:
            { return sym(sym.BASE_URL);
            }
            // fall through
          case 47: break;
          case 24:
            { return sym(sym.CONTAINS);
            }
            // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
