
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package translator;

import java.util.*;
import java_cup.runtime.*;
import translator.ast.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\065\000\002\002\004\000\002\002\005\000\002\003" +
    "\002\000\002\003\007\000\002\006\002\000\002\006\003" +
    "\000\002\004\002\000\002\004\004\000\002\005\006\000" +
    "\002\005\007\000\002\005\004\000\002\007\002\000\002" +
    "\007\010\000\002\007\010\000\002\007\005\000\002\007" +
    "\005\000\002\010\003\000\002\010\004\000\002\011\007" +
    "\000\002\012\003\000\002\012\004\000\002\013\005\000" +
    "\002\013\003\000\002\013\003\000\002\013\003\000\002" +
    "\013\003\000\002\013\003\000\002\014\005\000\002\014" +
    "\010\000\002\014\005\000\002\020\002\000\002\020\010" +
    "\000\002\020\005\000\002\015\005\000\002\015\010\000" +
    "\002\015\005\000\002\016\005\000\002\016\011\000\002" +
    "\016\005\000\002\017\005\000\002\017\011\000\002\017" +
    "\005\000\002\021\002\000\002\021\010\000\002\022\002" +
    "\000\002\022\007\000\002\022\007\000\002\023\007\000" +
    "\002\023\011\000\002\023\007\000\002\023\007\000\002" +
    "\023\010\000\002\023\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\174\000\010\004\004\007\uffff\010\uffff\001\002\000" +
    "\004\023\156\001\002\000\006\007\ufff6\010\ufff6\001\002" +
    "\000\004\002\007\001\002\000\004\002\001\001\002\000" +
    "\006\007\011\010\012\001\002\000\010\003\146\030\147" +
    "\031\150\001\002\000\004\031\016\001\002\000\006\002" +
    "\000\010\012\001\002\000\006\002\ufff1\010\ufff1\001\002" +
    "\000\006\002\ufff0\010\ufff0\001\002\000\004\023\017\001" +
    "\002\000\014\011\030\012\027\013\020\014\024\015\022" +
    "\001\002\000\004\027\136\001\002\000\016\011\uffe9\012" +
    "\uffe9\013\uffe9\014\uffe9\015\uffe9\024\uffe9\001\002\000\010" +
    "\006\111\016\107\017\110\001\002\000\016\011\030\012" +
    "\027\013\020\014\024\015\022\024\106\001\002\000\004" +
    "\027\076\001\002\000\016\011\uffee\012\uffee\013\uffee\014" +
    "\uffee\015\uffee\024\uffee\001\002\000\016\011\uffeb\012\uffeb" +
    "\013\uffeb\014\uffeb\015\uffeb\024\uffeb\001\002\000\004\027" +
    "\053\001\002\000\004\027\034\001\002\000\016\011\uffea" +
    "\012\uffea\013\uffea\014\uffea\015\uffea\024\uffea\001\002\000" +
    "\016\011\uffe8\012\uffe8\013\uffe8\014\uffe8\015\uffe8\024\uffe8" +
    "\001\002\000\016\011\uffe7\012\uffe7\013\uffe7\014\uffe7\015" +
    "\uffe7\024\uffe7\001\002\000\012\003\036\015\037\023\035" +
    "\025\040\001\002\000\010\006\uffe3\017\uffe3\024\uffe3\001" +
    "\002\000\016\011\uffe4\012\uffe4\013\uffe4\014\uffe4\015\uffe4" +
    "\024\uffe4\001\002\000\016\011\uffec\012\uffec\013\uffec\014" +
    "\uffec\015\uffec\024\uffec\001\002\000\016\011\uffe6\012\uffe6" +
    "\013\uffe6\014\uffe6\015\uffe6\024\uffe6\001\002\000\010\006" +
    "\044\017\042\024\043\001\002\000\004\003\052\001\002" +
    "\000\004\025\051\001\002\000\004\027\045\001\002\000" +
    "\004\022\046\001\002\000\004\027\047\001\002\000\004" +
    "\025\050\001\002\000\010\006\uffe2\017\uffe2\024\uffe2\001" +
    "\002\000\016\011\uffe5\012\uffe5\013\uffe5\014\uffe5\015\uffe5" +
    "\024\uffe5\001\002\000\010\006\uffe1\017\uffe1\024\uffe1\001" +
    "\002\000\010\003\055\023\054\025\056\001\002\000\010" +
    "\006\uffd7\017\uffd7\024\uffd7\001\002\000\016\011\uffdb\012" +
    "\uffdb\013\uffdb\014\uffdb\015\uffdb\024\uffdb\001\002\000\016" +
    "\011\uffdd\012\uffdd\013\uffdd\014\uffdd\015\uffdd\024\uffdd\001" +
    "\002\000\010\006\061\017\uffd5\024\uffd5\001\002\000\006" +
    "\017\066\024\067\001\002\000\004\027\062\001\002\000" +
    "\004\022\063\001\002\000\004\027\064\001\002\000\004" +
    "\025\065\001\002\000\010\006\uffd6\017\uffd6\024\uffd6\001" +
    "\002\000\004\022\071\001\002\000\004\025\070\001\002" +
    "\000\016\011\uffdc\012\uffdc\013\uffdc\014\uffdc\015\uffdc\024" +
    "\uffdc\001\002\000\006\027\072\030\073\001\002\000\004" +
    "\025\075\001\002\000\004\025\074\001\002\000\006\017" +
    "\uffd3\024\uffd3\001\002\000\006\017\uffd4\024\uffd4\001\002" +
    "\000\010\003\100\023\077\025\101\001\002\000\010\006" +
    "\uffe3\017\uffe3\024\uffe3\001\002\000\016\011\uffde\012\uffde" +
    "\013\uffde\014\uffde\015\uffde\024\uffde\001\002\000\016\011" +
    "\uffe0\012\uffe0\013\uffe0\014\uffe0\015\uffe0\024\uffe0\001\002" +
    "\000\010\006\044\017\042\024\103\001\002\000\004\025" +
    "\104\001\002\000\016\011\uffdf\012\uffdf\013\uffdf\014\uffdf" +
    "\015\uffdf\024\uffdf\001\002\000\016\011\uffed\012\uffed\013" +
    "\uffed\014\uffed\015\uffed\024\uffed\001\002\000\006\002\uffef" +
    "\010\uffef\001\002\000\006\021\125\022\124\001\002\000" +
    "\004\020\121\001\002\000\004\027\112\001\002\000\006" +
    "\020\114\022\113\001\002\000\004\027\117\001\002\000" +
    "\004\027\115\001\002\000\004\025\116\001\002\000\016" +
    "\011\uffcd\012\uffcd\013\uffcd\014\uffcd\015\uffcd\024\uffcd\001" +
    "\002\000\004\025\120\001\002\000\016\011\uffce\012\uffce" +
    "\013\uffce\014\uffce\015\uffce\024\uffce\001\002\000\004\027" +
    "\122\001\002\000\004\025\123\001\002\000\016\011\uffcf" +
    "\012\uffcf\013\uffcf\014\uffcf\015\uffcf\024\uffcf\001\002\000" +
    "\006\027\132\030\133\001\002\000\004\030\126\001\002" +
    "\000\004\026\127\001\002\000\004\030\130\001\002\000" +
    "\004\025\131\001\002\000\016\011\uffd1\012\uffd1\013\uffd1" +
    "\014\uffd1\015\uffd1\024\uffd1\001\002\000\004\025\135\001" +
    "\002\000\004\025\134\001\002\000\016\011\uffd2\012\uffd2" +
    "\013\uffd2\014\uffd2\015\uffd2\024\uffd2\001\002\000\016\011" +
    "\uffd0\012\uffd0\013\uffd0\014\uffd0\015\uffd0\024\uffd0\001\002" +
    "\000\010\003\140\023\137\025\141\001\002\000\010\006" +
    "\uffd7\017\uffd7\024\uffd7\001\002\000\016\011\uffd8\012\uffd8" +
    "\013\uffd8\014\uffd8\015\uffd8\024\uffd8\001\002\000\016\011" +
    "\uffda\012\uffda\013\uffda\014\uffda\015\uffda\024\uffda\001\002" +
    "\000\010\006\061\017\uffd5\024\uffd5\001\002\000\006\017" +
    "\066\024\144\001\002\000\004\025\145\001\002\000\016" +
    "\011\uffd9\012\uffd9\013\uffd9\014\uffd9\015\uffd9\024\uffd9\001" +
    "\002\000\006\007\ufff2\010\ufff2\001\002\000\006\007\ufff3" +
    "\010\ufff3\001\002\000\004\022\151\001\002\000\006\027" +
    "\152\030\153\001\002\000\004\025\155\001\002\000\004" +
    "\025\154\001\002\000\006\007\ufff4\010\ufff4\001\002\000" +
    "\006\007\ufff5\010\ufff5\001\002\000\012\003\ufffb\005\ufffb" +
    "\006\ufffb\024\ufffb\001\002\000\012\003\161\005\164\006" +
    "\163\024\162\001\002\000\012\003\ufffa\005\ufffa\006\ufffa" +
    "\024\ufffa\001\002\000\004\025\176\001\002\000\010\007" +
    "\ufffd\010\ufffd\025\175\001\002\000\004\027\170\001\002" +
    "\000\004\022\165\001\002\000\004\027\166\001\002\000" +
    "\004\025\167\001\002\000\012\003\ufff9\005\ufff9\006\ufff9" +
    "\024\ufff9\001\002\000\004\022\171\001\002\000\004\027" +
    "\172\001\002\000\004\025\173\001\002\000\012\003\ufff8" +
    "\005\ufff8\006\ufff8\024\ufff8\001\002\000\006\007\ufffe\010" +
    "\ufffe\001\002\000\006\007\ufffc\010\ufffc\001\002\000\012" +
    "\003\ufff7\005\ufff7\006\ufff7\024\ufff7\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\174\000\006\002\005\003\004\001\001\000\002\001" +
    "\001\000\004\007\007\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\010\012\011\013\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\014\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\012" +
    "\022\013\024\014\025\015\030\016\020\017\031\023\032" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\013\104\014\025\015\030\016\020\017\031" +
    "\023\032\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\020\040\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\021\056\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\022\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\020\101\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\021\141\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\022\142\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\156\001\001\000\004\005\157\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\006\173\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  // Accumulators for config and variables
  public String baseUrl = null;
  public Map<String,String> defaultHeaders = new LinkedHashMap<>();
  public Map<String,String> variables = new LinkedHashMap<>();
  private Set<String> testNames = new HashSet<>();

  // Track last three scanned token symbols to improve error diagnostics
  private int tok0 = -1, tok1 = -1, tok2 = -1; // tok2 = last, tok1 = prev, tok0 = prev-prev

  @Override
  public java_cup.runtime.Symbol scan() throws Exception {
    java_cup.runtime.Symbol s = super.scan();
    if (s != null) {
      tok0 = tok1;
      tok1 = tok2;
      tok2 = s.sym;
    }
    return s;
  }

  // Helper exception type (defined in src/main/java/translator/ParseException.java)
  private ParseException errorAt(Symbol sym, String msg) {
    int ln = sym != null ? sym.left : -1;
    int col = sym != null ? sym.right : -1;
    return new ParseException((ln > 0 ? ("Line " + ln + ": ") : "") + msg);
  }

  public void report_error(String message, Object info) {
    Symbol s = (info instanceof Symbol) ? (Symbol) info : null;
    throw errorAt(s, message);
  }

  public void report_fatal_error(String message, Object info) throws Exception {
    report_error(message, info);
  }

  public void syntax_error(Symbol cur_token) {
    // Map two specific contexts to the required messages
    // 1) let NUMBER ... → expected IDENT after 'let'
    if ((tok1 == sym.LET && cur_token != null && cur_token.sym == sym.NUMBER)
        || (tok0 == sym.LET && tok1 == sym.NUMBER && cur_token != null && cur_token.sym == sym.IDENT)) {
      throw errorAt(cur_token, "expected IDENT after 'let'");
    }
    // 2) Missing ';' after request before an assertion or block terminator
    if (cur_token != null) {
      boolean nextLooksLikeAssertionOrEnd = (cur_token.sym == sym.EXPECT || cur_token.sym == sym.STATUS || cur_token.sym == sym.TEST || cur_token.sym == sym.RBRACE);
      // Case A: immediately after GET/POST/... path
      if (tok0 == sym.GET && tok1 == sym.STRING && nextLooksLikeAssertionOrEnd) {
        throw errorAt(cur_token, "expected ';' after request");
      }
      // Case B: we've already seen EXPECT (e.g., GET STRING EXPECT STATUS ...)
      if (tok0 == sym.STRING && tok1 == sym.EXPECT && (cur_token.sym == sym.STATUS || cur_token.sym == sym.BODY || cur_token.sym == sym.HEADER)) {
        throw errorAt(cur_token, "expected ';' after request");
      }
      // Case C: parser already shifted EXPECT STATUS and sees '='
      if (tok0 == sym.EXPECT && tok1 == sym.STATUS && cur_token.sym == sym.EQ) {
        throw errorAt(cur_token, "expected ';' after request");
      }
    }
    throw errorAt(cur_token, "syntax error");
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= opt_config var_decls tests 
            {
              Program RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List<TestBlock> a = (List<TestBlock>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Program(baseUrl, defaultHeaders, variables, a); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // opt_config ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_config",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // opt_config ::= CONFIG LBRACE config_items RBRACE opt_semi 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_config",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // opt_semi ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_semi",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // opt_semi ::= SEMI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_semi",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // config_items ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_items",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // config_items ::= config_items config_item 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_items",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // config_item ::= BASE_URL EQ STRING SEMI 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 baseUrl = s; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_item",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // config_item ::= HEADER STRING EQ STRING SEMI 
            {
              Object RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String k = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 defaultHeaders.put(k, v); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_item",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // config_item ::= error SEMI 
            {
              Object RESULT =null;
		 report_error("expected 'base_url' or 'header' in config", null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_item",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // var_decls ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decls",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // var_decls ::= var_decls LET IDENT EQ STRING SEMI 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         if (variables.containsKey(id)) report_error("duplicate variable '"+id+"'", null);
         variables.put(id, s);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decls",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // var_decls ::= var_decls LET IDENT EQ NUMBER SEMI 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         if (variables.containsKey(id)) report_error("duplicate variable '"+id+"'", null);
         variables.put(id, Integer.toString(n));
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decls",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // var_decls ::= var_decls LET NUMBER 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
         report_error("expected IDENT after 'let'", null);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decls",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // var_decls ::= var_decls LET error 
            {
              Object RESULT =null;
		
         report_error("expected IDENT after 'let'", null);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decls",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // tests ::= test_block 
            {
              List<TestBlock> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		TestBlock a = (TestBlock)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
         List<TestBlock> list = new ArrayList<>();
         if (testNames.contains(a.name)) report_error("Duplicate test '"+a.name+"'", null);
         testNames.add(a.name);
         list.add(a);
         RESULT = list;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tests",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tests ::= tests test_block 
            {
              List<TestBlock> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<TestBlock> l = (List<TestBlock>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		TestBlock a = (TestBlock)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
         if (testNames.contains(a.name)) report_error("Duplicate test '"+a.name+"'", null);
         testNames.add(a.name);
         l.add(a);
         RESULT = l;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tests",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // test_block ::= TEST IDENT LBRACE statements RBRACE 
            {
              TestBlock RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<Statement> l = (List<Statement>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         int req=0, asrt=0;
         for (Statement s : l) {
           if (s != null && ("GET".equals(s.type) || "POST".equals(s.type) || "PUT".equals(s.type) || "DELETE".equals(s.type))) req++;
           else if (s instanceof Assertion) asrt++;
         }
         if (req < 1 || asrt < 2) report_error("Test '"+n+"' must contain at least 1 request and at least 2 assertions", null);
         RESULT = new TestBlock(n, l);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("test_block",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // statements ::= statement 
            {
              List<Statement> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
         List<Statement> list = new ArrayList<>();
         list.add(s);
         RESULT = list;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statements",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // statements ::= statements statement 
            {
              List<Statement> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<Statement> l = (List<Statement>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
         l.add(s);
         RESULT = l;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statements",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // statement ::= GET STRING EXPECT 
            {
              Statement RESULT =null;
		 report_error("expected ';' after request", null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // statement ::= get_stmt 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = s; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // statement ::= delete_stmt 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = s; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // statement ::= post_stmt 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = s; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // statement ::= put_stmt 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = s; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // statement ::= assertion 
            {
              Statement RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Assertion a = (Assertion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // get_stmt ::= GET STRING SEMI 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = new Statement("GET", u, null, new LinkedHashMap<String,String>());
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("get_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // get_stmt ::= GET STRING LBRACE get_block RBRACE SEMI 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Map<String,String> h = (Map<String,String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
         RESULT = new Statement("GET", u, null, h);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("get_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // get_stmt ::= GET STRING error 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         report_error("expected ';' after request", null);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("get_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // get_block ::= 
            {
              Map<String,String> RESULT =null;
		
         RESULT = new LinkedHashMap<String,String>();
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("get_block",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // get_block ::= get_block HEADER STRING EQ STRING SEMI 
            {
              Map<String,String> RESULT =null;
		int hmleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int hmright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Map<String,String> hm = (Map<String,String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int kleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String k = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         hm.put(k, v);
         RESULT = hm;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("get_block",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // get_block ::= get_block BODY error 
            {
              Map<String,String> RESULT =null;
		int hmleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int hmright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Map<String,String> hm = (Map<String,String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
         report_error("only 'header' allowed in request block for GET", null);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("get_block",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // delete_stmt ::= DELETE STRING SEMI 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = new Statement("DELETE", u, null, new LinkedHashMap<String,String>());
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("delete_stmt",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // delete_stmt ::= DELETE STRING LBRACE get_block RBRACE SEMI 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Map<String,String> h = (Map<String,String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
         RESULT = new Statement("DELETE", u, null, h);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("delete_stmt",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // delete_stmt ::= DELETE STRING error 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         report_error("expected ';' after request", null);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("delete_stmt",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // post_stmt ::= POST STRING SEMI 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = new Statement("POST", u, null, new LinkedHashMap<String,String>());
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("post_stmt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // post_stmt ::= POST STRING LBRACE headers_opt opt_body RBRACE SEMI 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Map<String,String> h = (Map<String,String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
         Statement st = new Statement("POST", u, b, h);
         RESULT = st;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("post_stmt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // post_stmt ::= POST STRING error 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         report_error("expected ';' after request", null);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("post_stmt",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // put_stmt ::= PUT STRING SEMI 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = new Statement("PUT", u, null, new LinkedHashMap<String,String>());
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("put_stmt",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // put_stmt ::= PUT STRING LBRACE headers_opt opt_body RBRACE SEMI 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Map<String,String> h = (Map<String,String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
         Statement st = new Statement("PUT", u, b, h);
         RESULT = st;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("put_stmt",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // put_stmt ::= PUT STRING error 
            {
              Statement RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String u = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         report_error("expected ';' after request", null);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("put_stmt",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // headers_opt ::= 
            {
              Map<String,String> RESULT =null;
		
         RESULT = new LinkedHashMap<String,String>();
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("headers_opt",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // headers_opt ::= headers_opt HEADER STRING EQ STRING SEMI 
            {
              Map<String,String> RESULT =null;
		int hmleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int hmright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Map<String,String> hm = (Map<String,String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int kleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String k = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         hm.put(k, v);
         RESULT = hm;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("headers_opt",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // opt_body ::= 
            {
              String RESULT =null;
		
         RESULT = null;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_body",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // opt_body ::= opt_body BODY EQ STRING SEMI 
            {
              String RESULT =null;
		int obleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int obright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String ob = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = s;
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_body",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // opt_body ::= opt_body BODY EQ NUMBER SEMI 
            {
              String RESULT =null;
		int obleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int obright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String ob = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         report_error("expected STRING after 'body ='", null);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_body",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // assertion ::= EXPECT STATUS EQ NUMBER SEMI 
            {
              Assertion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = new Assertion("status_eq", Integer.toString(n));
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // assertion ::= EXPECT STATUS IN NUMBER DOTDOT NUMBER SEMI 
            {
              Assertion RESULT =null;
		int loleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int loright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Integer lo = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int hileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int hiright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer hi = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = Assertion.statusIn(lo, hi);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // assertion ::= EXPECT STATUS EQ STRING SEMI 
            {
              Assertion RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         report_error("expected NUMBER for status", null);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // assertion ::= EXPECT BODY CONTAINS STRING SEMI 
            {
              Assertion RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = new Assertion("body_contains", s);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // assertion ::= EXPECT HEADER STRING EQ STRING SEMI 
            {
              Assertion RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String k = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = Assertion.headerEq(k, v);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // assertion ::= EXPECT HEADER STRING CONTAINS STRING SEMI 
            {
              Assertion RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String k = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
         RESULT = Assertion.headerContains(k, s);
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
