// Generated by TestLang++ Translator
// Source: examples\\example_full.test
// Generated at: Fri Oct 24 20:45:40 IST 2025

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import java.net.http.*; import java.net.*; import java.time.Duration;
import java.nio.charset.StandardCharsets; import java.util.*;

public class GeneratedTests {
  static String BASE = "http://localhost:8080";
  static Map<String,String> DEFAULT_HEADERS = new LinkedHashMap<>();
  static HttpClient client;

  @BeforeAll static void setup() {
    client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build();
    DEFAULT_HEADERS.put("Content-Type","application/json");
    DEFAULT_HEADERS.put("X-App","TestLangDemo");
  }

  @Test
  void test_Login() throws Exception {
    HttpResponse<String> resp = null;
    HttpRequest.Builder b = HttpRequest.newBuilder(URI.create(resolveUrl(BASE, "/api/login")))
      .timeout(Duration.ofSeconds(10))
      .POST(HttpRequest.BodyPublishers.ofString("{ \"username\": \"admin\", \"password\": \"1234\" }"));
    for (var e: DEFAULT_HEADERS.entrySet()) b.header(e.getKey(), e.getValue());
    resp = client.send(b.build(), HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));

    assertEquals(200, resp.statusCode());
    assertTrue(resp.headers().firstValue("Content-Type").orElse("").contains("json"));
    assertTrue(resp.body().contains("\"token\":"));
  }

  @Test
  void test_GetUser() throws Exception {
    HttpResponse<String> resp = null;
    HttpRequest.Builder b = HttpRequest.newBuilder(URI.create(resolveUrl(BASE, "/api/users/42")))
      .timeout(Duration.ofSeconds(10))
      .GET();
    for (var e: DEFAULT_HEADERS.entrySet()) b.header(e.getKey(), e.getValue());
    resp = client.send(b.build(), HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));

    assertTrue(resp.statusCode() >= 200 && resp.statusCode() <= 299);
    assertTrue(resp.body().contains("\"id\": 42"));
  }

  @Test
  void test_UpdateUser() throws Exception {
    HttpResponse<String> resp = null;
    HttpRequest.Builder b = HttpRequest.newBuilder(URI.create(resolveUrl(BASE, "/api/users/42")))
      .timeout(Duration.ofSeconds(10))
      .PUT(HttpRequest.BodyPublishers.ofString("{ \"role\": \"ADMIN\" }"));
    for (var e: DEFAULT_HEADERS.entrySet()) b.header(e.getKey(), e.getValue());
    b.setHeader("X-Trace", "abc-42");
    resp = client.send(b.build(), HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));

    assertEquals(200, resp.statusCode());
    assertEquals("TestLangDemo", resp.headers().firstValue("X-App").orElse(""));
    assertTrue(resp.headers().firstValue("Content-Type").orElse("").contains("json"));
    assertTrue(resp.body().contains("\"updated\": true"));
    assertTrue(resp.body().contains("\"role\": \"ADMIN\""));
  }

  private static String resolveUrl(String base, String path) {
    if (path == null || path.isEmpty()) return base;
    if (path.startsWith("http://") || path.startsWith("https://")) return path;
    if (base == null || base.isEmpty()) {
      if (path.startsWith("/")) throw new IllegalStateException("No base_url configured; path must be absolute");
      return path;
    }
    if (path.startsWith("/")) return base + path;
    if (base.endsWith("/")) return base + path;
    return base + "/" + path;
  }
}
